[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/healthcheck"
healthcheckTimeout = 100
startCommand = "uvicorn api.index:app --host 0.0.0.0 --port $PORT"
